global:
  scrape_interval: 15s  # How often to scrape targets by default.

scrape_configs:
  - job_name: 'flask-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['web-app-service:5000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-db:5432']
